### ISSUE TITLE
링크 색상 변경

### ISSUE THREAD

**Issue by phg98** [hacktoberfestkorea/hacktoberfestkorea#129]
**문제점**
링크가 빨간색이어서 보기 안 좋다.
Hacktoberfest 대표 색상중에 하나를 사용하려고 했는데,
mkdocs에서 색상지정하는 방법을 몰라서 그냥 mkdocs.yml 파일에 아래와 같이 red로 지정했음.
```
theme:
  name: material
  language: kr
  custom_dir: 'theme'
  palette:
    scheme: default
    primary: red
```
**개선방안**
HF'21-Promo-Kit/Hacktoberfest-Brand-Guidelines-2021.pdf 문서의 대표색상을 참고하여 보기 좋은 색상으로 
링크가 표시되도록 하면 좋겠다.
